added validation for things in tool submission script, edited readme script to be similar to tool approval workflow

diff --git a/.github/workflows/update_readme.yml b/.github/workflows/update_readme.yml
--- a/.github/workflows/update_readme.yml
+++ b/.github/workflows/update_readme.yml
@@ -34,11 +34,22 @@ jobs:
           echo "commit_username=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
 
       - name: Commit changes to README
+        if: success()
         run: |
           git config --local user.email "${{ steps.commit_info.outputs.commit_email }}"
           git config --local user.name "${{ steps.commit_info.outputs.commit_username }}"
           git add README.md
-          git commit -m "Update README with approved tools"
-          git push
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          git diff-index --quiet HEAD || (git commit -a -m "Update README with approved tools" --allow-empty)
+
+      - name: Push Changes
+        if: success()
+        uses: ad-m/github-push-action@v0.6.0
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: main
+
+      - name: Problem With Action
+        if: failure()
+        run: |
+          echo "Error updating README. Please check the logs for details."
+          exit 1
